# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import MergeATSClient
from MergeATSClient.models.activity import Activity  # noqa: E501
from MergeATSClient.rest import ApiException

class TestActivity(unittest.TestCase):
    """Activity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Activity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = MergeATSClient.models.activity.Activity()  # noqa: E501
        if include_optional :
            return Activity(
                id = 'ecbe05ac-62a3-46c5-ab31-4b478b37d1b4', 
                remote_id = '6', 
                user = '9d892439-5fab-4dbb-8bd8-34f7f96c7912', 
                remote_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                activity_type = NOTE, 
                subject = 'Henry's applicant status', 
                body = 'Candidate will only join if we provide a Barry's subsidy.', 
                visibility = PRIVATE
            )
        else :
            return Activity(
        )

    def testActivity(self):
        """Test Activity"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
