"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.email_address_request import EmailAddressRequest
from MergeATSClient.model.phone_number_request import PhoneNumberRequest
from MergeATSClient.model.url_request import UrlRequest
globals()['EmailAddressRequest'] = EmailAddressRequest
globals()['PhoneNumberRequest'] = PhoneNumberRequest
globals()['UrlRequest'] = UrlRequest
from MergeATSClient.model.candidate_request import CandidateRequest
from MergeATSClient.api_client import ApiClient


class TestCandidateRequest(unittest.TestCase):
    """CandidateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCandidateRequest(self):
        """Test CandidateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CandidateRequest()  # noqa: E501

        """
        No test json responses were defined for CandidateRequest
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (CandidateRequest,), False)

        assert deserialized is not None



if __name__ == '__main__':
    unittest.main()
