# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeATSClient
from MergeATSClient.api.tags_api import TagsApi  # noqa: E501
from MergeATSClient.rest import ApiException


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = MergeATSClient.api.tags_api.TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tags_create(self):
        """Test case for tags_create

        """
        pass

    def test_tags_destroy(self):
        """Test case for tags_destroy

        """
        pass

    def test_tags_list(self):
        """Test case for tags_list

        """
        pass

    def test_tags_partial_update(self):
        """Test case for tags_partial_update

        """
        pass

    def test_tags_retrieve(self):
        """Test case for tags_retrieve

        """
        pass

    def test_tags_update(self):
        """Test case for tags_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
