"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sync_status import SyncStatus
globals()['SyncStatus'] = SyncStatus
from openapi_client.model.paginated_sync_status_list import PaginatedSyncStatusList


class TestPaginatedSyncStatusList(unittest.TestCase):
    """PaginatedSyncStatusList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedSyncStatusList(self):
        """Test PaginatedSyncStatusList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedSyncStatusList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
