"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeATSClient
from MergeATSClient.model.department_request import DepartmentRequest


class TestDepartmentRequest(unittest.TestCase):
    """DepartmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDepartmentRequest(self):
        """Test DepartmentRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DepartmentRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
