"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeATSClient
from MergeATSClient.api.candidates_api import CandidatesApi  # noqa: E501


class TestCandidatesApi(unittest.TestCase):
    """CandidatesApi unit test stubs"""

    def setUp(self):
        self.api = CandidatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_candidates_create(self):
        """Test case for candidates_create

        """
        pass

    def test_candidates_ignore_create(self):
        """Test case for candidates_ignore_create

        """
        pass

    def test_candidates_list(self):
        """Test case for candidates_list

        """
        pass

    def test_candidates_meta_post_retrieve(self):
        """Test case for candidates_meta_post_retrieve

        """
        pass

    def test_candidates_retrieve(self):
        """Test case for candidates_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
