# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import MergeATSClient
from MergeATSClient.models.paginated_scheduled_interview_list import PaginatedScheduledInterviewList  # noqa: E501
from MergeATSClient.rest import ApiException

class TestPaginatedScheduledInterviewList(unittest.TestCase):
    """PaginatedScheduledInterviewList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PaginatedScheduledInterviewList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = MergeATSClient.models.paginated_scheduled_interview_list.PaginatedScheduledInterviewList()  # noqa: E501
        if include_optional :
            return PaginatedScheduledInterviewList(
                next = '0', 
                previous = '0', 
                results = [
                    MergeATSClient.models.scheduled_interview.ScheduledInterview(
                        id = 'b8faf072-98b9-4445-8a9a-6b4950efca19', 
                        remote_id = '3', 
                        application = '0', 
                        organizer = '52bf9b5e-0beb-4f6f-8a72-cd4dca7ca633', 
                        interviewers = ["f9813dd5-e70b-484c-91d8-00acd6065b07","89a86fcf-d540-4e6b-ac3d-ce07c4ec9b3c"], 
                        location = 'Embarcadero Center 2', 
                        start_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        remote_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        remote_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = SCHEDULED, )
                    ]
            )
        else :
            return PaginatedScheduledInterviewList(
        )

    def testPaginatedScheduledInterviewList(self):
        """Test PaginatedScheduledInterviewList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
