"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeATSClient
from MergeATSClient.api.delete_account_api import DeleteAccountApi  # noqa: E501


class TestDeleteAccountApi(unittest.TestCase):
    """DeleteAccountApi unit test stubs"""

    def setUp(self):
        self.api = DeleteAccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_account_create(self):
        """Test case for delete_account_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
