"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.attachment_write_model_request import AttachmentWriteModelRequest
globals()['AttachmentWriteModelRequest'] = AttachmentWriteModelRequest
from MergeATSClient.model.attachment_write_request import AttachmentWriteRequest
from MergeATSClient.api_client import ApiClient


class TestAttachmentWriteRequest(unittest.TestCase):
    """AttachmentWriteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachmentWriteRequest(self):
        """Test AttachmentWriteRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachmentWriteRequest()  # noqa: E501

        """
        No test json responses were defined for AttachmentWriteRequest
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (AttachmentWriteRequest,), False)

        assert deserialized is not None

        assert deserialized.model is not None
        assert deserialized.remote_user_id is not None


if __name__ == '__main__':
    unittest.main()
