"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeATSClient
from MergeATSClient.model.status007_enum import Status007Enum


class TestStatus007Enum(unittest.TestCase):
    """Status007Enum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatus007Enum(self):
        """Test Status007Enum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Status007Enum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
