"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.categories_enum import CategoriesEnum
globals()['CategoriesEnum'] = CategoriesEnum
from MergeATSClient.model.end_user_details_request import EndUserDetailsRequest
from MergeATSClient.api_client import ApiClient


class TestEndUserDetailsRequest(unittest.TestCase):
    """EndUserDetailsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndUserDetailsRequest(self):
        """Test EndUserDetailsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EndUserDetailsRequest()  # noqa: E501

        """
        No test json responses were defined for EndUserDetailsRequest
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (EndUserDetailsRequest,), False)

        assert deserialized is not None

        assert deserialized.end_user_email_address is not None
        assert deserialized.end_user_organization_name is not None
        assert deserialized.end_user_origin_id is not None
        assert deserialized.categories is not None


if __name__ == '__main__':
    unittest.main()
