"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeATSClient
from MergeATSClient.model.status757_enum import Status757Enum


class TestStatus757Enum(unittest.TestCase):
    """Status757Enum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatus757Enum(self):
        """Test Status757Enum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Status757Enum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
