"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.activity_type_enum import ActivityTypeEnum
from MergeATSClient.api_client import ApiClient


class TestActivityTypeEnum(unittest.TestCase):
    """ActivityTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityTypeEnum(self):
        """Test ActivityTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivityTypeEnum()  # noqa: E501

        # no tests for enums
        pass

if __name__ == '__main__':
    unittest.main()
