# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import MergeATSClient
from MergeATSClient.models.patched_attachment import PatchedAttachment  # noqa: E501
from MergeATSClient.rest import ApiException

class TestPatchedAttachment(unittest.TestCase):
    """PatchedAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PatchedAttachment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = MergeATSClient.models.patched_attachment.PatchedAttachment()  # noqa: E501
        if include_optional :
            return PatchedAttachment(
                id = 'c640b80b-fac9-409f-aa19-1f9221aec445', 
                remote_id = '11167', 
                file_name = 'Candidate Resume', 
                file_url = 'http://alturl.com/p749b'
            )
        else :
            return PatchedAttachment(
        )

    def testPatchedAttachment(self):
        """Test PatchedAttachment"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
