"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.scorecard_request import ScorecardRequest


class TestScorecardRequest(unittest.TestCase):
    """ScorecardRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScorecardRequest(self):
        """Test ScorecardRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScorecardRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
