"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeATSClient
from MergeATSClient.api.applications_api import ApplicationsApi  # noqa: E501


class TestApplicationsApi(unittest.TestCase):
    """ApplicationsApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_applications_create(self):
        """Test case for applications_create

        """
        pass

    def test_applications_list(self):
        """Test case for applications_list

        """
        pass

    def test_applications_meta_post_retrieve(self):
        """Test case for applications_meta_post_retrieve

        """
        pass

    def test_applications_retrieve(self):
        """Test case for applications_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
