"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.application_request import ApplicationRequest
globals()['ApplicationRequest'] = ApplicationRequest
from MergeATSClient.model.application_endpoint_request import ApplicationEndpointRequest
from MergeATSClient.api_client import ApiClient


class TestApplicationEndpointRequest(unittest.TestCase):
    """ApplicationEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationEndpointRequest(self):
        """Test ApplicationEndpointRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationEndpointRequest()  # noqa: E501

        """
        No test json responses were defined for ApplicationEndpointRequest
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (ApplicationEndpointRequest,), False)

        assert deserialized is not None

        assert deserialized.model is not None
        assert deserialized.remote_user_id is not None


if __name__ == '__main__':
    unittest.main()
