# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeATSClient
from MergeATSClient.api.offices_api import OfficesApi  # noqa: E501
from MergeATSClient.rest import ApiException


class TestOfficesApi(unittest.TestCase):
    """OfficesApi unit test stubs"""

    def setUp(self):
        self.api = MergeATSClient.api.offices_api.OfficesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_offices_create(self):
        """Test case for offices_create

        """
        pass

    def test_offices_destroy(self):
        """Test case for offices_destroy

        """
        pass

    def test_offices_list(self):
        """Test case for offices_list

        """
        pass

    def test_offices_partial_update(self):
        """Test case for offices_partial_update

        """
        pass

    def test_offices_retrieve(self):
        """Test case for offices_retrieve

        """
        pass

    def test_offices_update(self):
        """Test case for offices_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
