"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.visibility_enum import VisibilityEnum
from MergeATSClient.api_client import ApiClient


class TestVisibilityEnum(unittest.TestCase):
    """VisibilityEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVisibilityEnum(self):
        """Test VisibilityEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VisibilityEnum()  # noqa: E501

        # no tests for enums
        pass

if __name__ == '__main__':
    unittest.main()
