# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeATSClient
from MergeATSClient.api.activities_api import ActivitiesApi  # noqa: E501
from MergeATSClient.rest import ApiException


class TestActivitiesApi(unittest.TestCase):
    """ActivitiesApi unit test stubs"""

    def setUp(self):
        self.api = MergeATSClient.api.activities_api.ActivitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activities_create(self):
        """Test case for activities_create

        """
        pass

    def test_activities_destroy(self):
        """Test case for activities_destroy

        """
        pass

    def test_activities_list(self):
        """Test case for activities_list

        """
        pass

    def test_activities_partial_update(self):
        """Test case for activities_partial_update

        """
        pass

    def test_activities_retrieve(self):
        """Test case for activities_retrieve

        """
        pass

    def test_activities_update(self):
        """Test case for activities_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
