"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.remote_data import RemoteData
globals()['RemoteData'] = RemoteData
from MergeATSClient.model.remote_user import RemoteUser
from MergeATSClient.api_client import ApiClient


class TestRemoteUser(unittest.TestCase):
    """RemoteUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoteUser(self):
        """Test RemoteUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RemoteUser()  # noqa: E501

        raw_json = """
            {"id": "b82302de-852e-4e60-b050-edf9da3b7c02", "remote_id": "344321", "first_name": "Shensi", "last_name": "Ding", "email": "hello@merge.dev", "disabled": false, "remote_created_at": "2020-11-10T00:00:00Z", "access_role": "SUPER_ADMIN", "remote_data": [{"path": "/users", "data": {"example": "Varies by platform"}}]}
        """

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (RemoteUser,), False)

        assert deserialized is not None



if __name__ == '__main__':
    unittest.main()
