"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeATSClient
from MergeATSClient.model.remote_key_for_regeneration_request import RemoteKeyForRegenerationRequest


class TestRemoteKeyForRegenerationRequest(unittest.TestCase):
    """RemoteKeyForRegenerationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoteKeyForRegenerationRequest(self):
        """Test RemoteKeyForRegenerationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RemoteKeyForRegenerationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
