# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeATSClient
from MergeATSClient.api.attachments_api import AttachmentsApi  # noqa: E501
from MergeATSClient.rest import ApiException


class TestAttachmentsApi(unittest.TestCase):
    """AttachmentsApi unit test stubs"""

    def setUp(self):
        self.api = MergeATSClient.api.attachments_api.AttachmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attachments_create(self):
        """Test case for attachments_create

        """
        pass

    def test_attachments_destroy(self):
        """Test case for attachments_destroy

        """
        pass

    def test_attachments_list(self):
        """Test case for attachments_list

        """
        pass

    def test_attachments_partial_update(self):
        """Test case for attachments_partial_update

        """
        pass

    def test_attachments_retrieve(self):
        """Test case for attachments_retrieve

        """
        pass

    def test_attachments_update(self):
        """Test case for attachments_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
