"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeATSClient
from MergeATSClient.model.attachment_request import AttachmentRequest


class TestAttachmentRequest(unittest.TestCase):
    """AttachmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachmentRequest(self):
        """Test AttachmentRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachmentRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
