# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import MergeATSClient
from MergeATSClient.models.office import Office  # noqa: E501
from MergeATSClient.rest import ApiException

class TestOffice(unittest.TestCase):
    """Office unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Office
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = MergeATSClient.models.office.Office()  # noqa: E501
        if include_optional :
            return Office(
                id = '9871b4a9-f5d2-4f3b-a66b-dfedbed42c46', 
                remote_id = '876556788', 
                name = 'Underground Bunker', 
                location = 'Embarcadero Center 2'
            )
        else :
            return Office(
        )

    def testOffice(self):
        """Test Office"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
