"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.url_type_enum import UrlTypeEnum
from MergeATSClient.api_client import ApiClient


class TestUrlTypeEnum(unittest.TestCase):
    """UrlTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUrlTypeEnum(self):
        """Test UrlTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UrlTypeEnum()  # noqa: E501

        # no tests for enums
        pass

if __name__ == '__main__':
    unittest.main()
