"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeATSClient
from MergeATSClient.model.status_a9f_enum import StatusA9fEnum


class TestStatusA9fEnum(unittest.TestCase):
    """StatusA9fEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusA9fEnum(self):
        """Test StatusA9fEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatusA9fEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
