"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.remote_user_request import RemoteUserRequest


class TestRemoteUserRequest(unittest.TestCase):
    """RemoteUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoteUserRequest(self):
        """Test RemoteUserRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RemoteUserRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
