# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import MergeATSClient
from MergeATSClient.models.phone_number import PhoneNumber  # noqa: E501
from MergeATSClient.rest import ApiException

class TestPhoneNumber(unittest.TestCase):
    """PhoneNumber unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PhoneNumber
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = MergeATSClient.models.phone_number.PhoneNumber()  # noqa: E501
        if include_optional :
            return PhoneNumber(
                value = '+3198675309', 
                phone_number_type = HOME
            )
        else :
            return PhoneNumber(
        )

    def testPhoneNumber(self):
        """Test PhoneNumber"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
