"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.attachment_request import AttachmentRequest
globals()['AttachmentRequest'] = AttachmentRequest
from MergeATSClient.model.attachment_endpoint_request import AttachmentEndpointRequest
from MergeATSClient.api_client import ApiClient


class TestAttachmentEndpointRequest(unittest.TestCase):
    """AttachmentEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachmentEndpointRequest(self):
        """Test AttachmentEndpointRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachmentEndpointRequest()  # noqa: E501

        """
        No test json responses were defined for AttachmentEndpointRequest
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (AttachmentEndpointRequest,), False)

        assert deserialized is not None

        assert deserialized.model is not None
        assert deserialized.remote_user_id is not None


if __name__ == '__main__':
    unittest.main()
