"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.disability_status_enum import DisabilityStatusEnum
from MergeATSClient.api_client import ApiClient


class TestDisabilityStatusEnum(unittest.TestCase):
    """DisabilityStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDisabilityStatusEnum(self):
        """Test DisabilityStatusEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DisabilityStatusEnum()  # noqa: E501

        # no tests for enums
        pass

if __name__ == '__main__':
    unittest.main()
