"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.scheduled_interview_request import ScheduledInterviewRequest


class TestScheduledInterviewRequest(unittest.TestCase):
    """ScheduledInterviewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduledInterviewRequest(self):
        """Test ScheduledInterviewRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScheduledInterviewRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
