"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.attachment_type_enum import AttachmentTypeEnum
from MergeATSClient.api_client import ApiClient


class TestAttachmentTypeEnum(unittest.TestCase):
    """AttachmentTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachmentTypeEnum(self):
        """Test AttachmentTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachmentTypeEnum()  # noqa: E501

        # no tests for enums
        pass

if __name__ == '__main__':
    unittest.main()
