"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.veteran_status_enum import VeteranStatusEnum
from MergeATSClient.api_client import ApiClient


class TestVeteranStatusEnum(unittest.TestCase):
    """VeteranStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVeteranStatusEnum(self):
        """Test VeteranStatusEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VeteranStatusEnum()  # noqa: E501

        # no tests for enums
        pass

if __name__ == '__main__':
    unittest.main()
