# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeATSClient
from MergeATSClient.api.reject_reasons_api import RejectReasonsApi  # noqa: E501
from MergeATSClient.rest import ApiException


class TestRejectReasonsApi(unittest.TestCase):
    """RejectReasonsApi unit test stubs"""

    def setUp(self):
        self.api = MergeATSClient.api.reject_reasons_api.RejectReasonsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reject_reasons_create(self):
        """Test case for reject_reasons_create

        """
        pass

    def test_reject_reasons_destroy(self):
        """Test case for reject_reasons_destroy

        """
        pass

    def test_reject_reasons_list(self):
        """Test case for reject_reasons_list

        """
        pass

    def test_reject_reasons_partial_update(self):
        """Test case for reject_reasons_partial_update

        """
        pass

    def test_reject_reasons_retrieve(self):
        """Test case for reject_reasons_retrieve

        """
        pass

    def test_reject_reasons_update(self):
        """Test case for reject_reasons_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
