"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeATSClient
from MergeATSClient.model.create_attachment import CreateAttachment


class TestCreateAttachment(unittest.TestCase):
    """CreateAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateAttachment(self):
        """Test CreateAttachment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateAttachment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
