# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import MergeATSClient
from MergeATSClient.models.paginated_scorecard_list import PaginatedScorecardList  # noqa: E501
from MergeATSClient.rest import ApiException

class TestPaginatedScorecardList(unittest.TestCase):
    """PaginatedScorecardList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PaginatedScorecardList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = MergeATSClient.models.paginated_scorecard_list.PaginatedScorecardList()  # noqa: E501
        if include_optional :
            return PaginatedScorecardList(
                next = '0', 
                previous = '0', 
                results = [
                    MergeATSClient.models.scorecard.Scorecard(
                        id = '3eab2f17-eeb1-450d-97f0-029d8be1e06f', 
                        remote_id = '22234', 
                        application = '2872ba14-4084-492b-be96-e5eee6fc33ef', 
                        interview = '52bf9b5e-0beb-4f6f-8a72-cd4dca7ca633', 
                        interviewer = 'bbb519a3-246e-4b95-b6b3-dba16107ba6b', 
                        remote_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        submitted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        overall_recommendation = STRONG_YES, )
                    ]
            )
        else :
            return PaginatedScorecardList(
        )

    def testPaginatedScorecardList(self):
        """Test PaginatedScorecardList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
