# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeATSClient
from MergeATSClient.api.jobs_api import JobsApi  # noqa: E501
from MergeATSClient.rest import ApiException


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self):
        self.api = MergeATSClient.api.jobs_api.JobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_jobs_create(self):
        """Test case for jobs_create

        """
        pass

    def test_jobs_destroy(self):
        """Test case for jobs_destroy

        """
        pass

    def test_jobs_list(self):
        """Test case for jobs_list

        """
        pass

    def test_jobs_partial_update(self):
        """Test case for jobs_partial_update

        """
        pass

    def test_jobs_retrieve(self):
        """Test case for jobs_retrieve

        """
        pass

    def test_jobs_update(self):
        """Test case for jobs_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
