"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.offer_status_enum import OfferStatusEnum
from MergeATSClient.api_client import ApiClient


class TestOfferStatusEnum(unittest.TestCase):
    """OfferStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOfferStatusEnum(self):
        """Test OfferStatusEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OfferStatusEnum()  # noqa: E501

        # no tests for enums
        pass

if __name__ == '__main__':
    unittest.main()
