"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeATSClient
from MergeATSClient.model.email_address_type_enum import EmailAddressTypeEnum
from MergeATSClient.api_client import ApiClient


class TestEmailAddressTypeEnum(unittest.TestCase):
    """EmailAddressTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmailAddressTypeEnum(self):
        """Test EmailAddressTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmailAddressTypeEnum()  # noqa: E501

        # no tests for enums
        pass

if __name__ == '__main__':
    unittest.main()
