# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import MergeATSClient
from MergeATSClient.models.paginated_attachment_list import PaginatedAttachmentList  # noqa: E501
from MergeATSClient.rest import ApiException

class TestPaginatedAttachmentList(unittest.TestCase):
    """PaginatedAttachmentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PaginatedAttachmentList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = MergeATSClient.models.paginated_attachment_list.PaginatedAttachmentList()  # noqa: E501
        if include_optional :
            return PaginatedAttachmentList(
                next = '0', 
                previous = '0', 
                results = [
                    MergeATSClient.models.attachment.Attachment(
                        id = 'c640b80b-fac9-409f-aa19-1f9221aec445', 
                        remote_id = '11167', 
                        file_name = 'Candidate Resume', 
                        file_url = 'http://alturl.com/p749b', )
                    ]
            )
        else :
            return PaginatedAttachmentList(
        )

    def testPaginatedAttachmentList(self):
        """Test PaginatedAttachmentList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
