"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeATSClient
from MergeATSClient.model.create_offer import CreateOffer


class TestCreateOffer(unittest.TestCase):
    """CreateOffer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateOffer(self):
        """Test CreateOffer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateOffer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
