"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeATSClient
from MergeATSClient.model.patched_application_request import PatchedApplicationRequest


class TestPatchedApplicationRequest(unittest.TestCase):
    """PatchedApplicationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedApplicationRequest(self):
        """Test PatchedApplicationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedApplicationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
