"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeATSClient
from MergeATSClient.api.scorecards_api import ScorecardsApi  # noqa: E501


class TestScorecardsApi(unittest.TestCase):
    """ScorecardsApi unit test stubs"""

    def setUp(self):
        self.api = ScorecardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_scorecards_list(self):
        """Test case for scorecards_list

        """
        pass

    def test_scorecards_retrieve(self):
        """Test case for scorecards_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
