"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeATSClient
from MergeATSClient.model.office import Office
globals()['Office'] = Office
from MergeATSClient.model.paginated_office_list import PaginatedOfficeList


class TestPaginatedOfficeList(unittest.TestCase):
    """PaginatedOfficeList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedOfficeList(self):
        """Test PaginatedOfficeList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedOfficeList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
