# coding: utf-8

# flake8: noqa
"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from MergeATSClient.models.access_role_enum import AccessRoleEnum
from MergeATSClient.models.account_token import AccountToken
from MergeATSClient.models.activity import Activity
from MergeATSClient.models.activity_type_enum import ActivityTypeEnum
from MergeATSClient.models.application import Application
from MergeATSClient.models.async_task_execution import AsyncTaskExecution
from MergeATSClient.models.async_task_execution_status_enum import AsyncTaskExecutionStatusEnum
from MergeATSClient.models.attachment import Attachment
from MergeATSClient.models.candidate import Candidate
from MergeATSClient.models.department import Department
from MergeATSClient.models.disability_status_enum import DisabilityStatusEnum
from MergeATSClient.models.eeoc import EEOC
from MergeATSClient.models.email_address import EmailAddress
from MergeATSClient.models.email_address_type_enum import EmailAddressTypeEnum
from MergeATSClient.models.end_user_details import EndUserDetails
from MergeATSClient.models.gender_enum import GenderEnum
from MergeATSClient.models.job import Job
from MergeATSClient.models.job_interview_stage import JobInterviewStage
from MergeATSClient.models.job_status_enum import JobStatusEnum
from MergeATSClient.models.link_token import LinkToken
from MergeATSClient.models.offer import Offer
from MergeATSClient.models.offer_status_enum import OfferStatusEnum
from MergeATSClient.models.office import Office
from MergeATSClient.models.overall_recommendation_enum import OverallRecommendationEnum
from MergeATSClient.models.paginated_activity_list import PaginatedActivityList
from MergeATSClient.models.paginated_application_list import PaginatedApplicationList
from MergeATSClient.models.paginated_async_task_execution_list import PaginatedAsyncTaskExecutionList
from MergeATSClient.models.paginated_attachment_list import PaginatedAttachmentList
from MergeATSClient.models.paginated_candidate_list import PaginatedCandidateList
from MergeATSClient.models.paginated_department_list import PaginatedDepartmentList
from MergeATSClient.models.paginated_eeoc_list import PaginatedEEOCList
from MergeATSClient.models.paginated_job_interview_stage_list import PaginatedJobInterviewStageList
from MergeATSClient.models.paginated_job_list import PaginatedJobList
from MergeATSClient.models.paginated_offer_list import PaginatedOfferList
from MergeATSClient.models.paginated_office_list import PaginatedOfficeList
from MergeATSClient.models.paginated_reject_reason_list import PaginatedRejectReasonList
from MergeATSClient.models.paginated_remote_user_list import PaginatedRemoteUserList
from MergeATSClient.models.paginated_scheduled_interview_list import PaginatedScheduledInterviewList
from MergeATSClient.models.paginated_scorecard_list import PaginatedScorecardList
from MergeATSClient.models.paginated_tag_list import PaginatedTagList
from MergeATSClient.models.phone_number import PhoneNumber
from MergeATSClient.models.phone_number_type_enum import PhoneNumberTypeEnum
from MergeATSClient.models.race_enum import RaceEnum
from MergeATSClient.models.reject_reason import RejectReason
from MergeATSClient.models.remote_user import RemoteUser
from MergeATSClient.models.scheduled_interview import ScheduledInterview
from MergeATSClient.models.scheduled_interview_status_enum import ScheduledInterviewStatusEnum
from MergeATSClient.models.scorecard import Scorecard
from MergeATSClient.models.source_enum import SourceEnum
from MergeATSClient.models.tag import Tag
from MergeATSClient.models.url import Url
from MergeATSClient.models.url_type_enum import UrlTypeEnum
from MergeATSClient.models.veteran_status_enum import VeteranStatusEnum
from MergeATSClient.models.visibility_enum import VisibilityEnum
