# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from MergeATSClient.configuration import Configuration


class PatchedOffice(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'remote_id': 'str',
        'name': 'str',
        'location': 'str'
    }

    attribute_map = {
        'id': 'id',
        'remote_id': 'remote_id',
        'name': 'name',
        'location': 'location'
    }

    def __init__(self, id=None, remote_id=None, name=None, location=None, local_vars_configuration=None):  # noqa: E501
        """PatchedOffice - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._remote_id = None
        self._name = None
        self._location = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.remote_id = remote_id
        self.name = name
        self.location = location

    @property
    def id(self):
        """Gets the id of this PatchedOffice.  # noqa: E501


        :return: The id of this PatchedOffice.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PatchedOffice.


        :param id: The id of this PatchedOffice.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def remote_id(self):
        """Gets the remote_id of this PatchedOffice.  # noqa: E501

        The third-party API ID of the matching object.  # noqa: E501

        :return: The remote_id of this PatchedOffice.  # noqa: E501
        :rtype: str
        """
        return self._remote_id

    @remote_id.setter
    def remote_id(self, remote_id):
        """Sets the remote_id of this PatchedOffice.

        The third-party API ID of the matching object.  # noqa: E501

        :param remote_id: The remote_id of this PatchedOffice.  # noqa: E501
        :type: str
        """

        self._remote_id = remote_id

    @property
    def name(self):
        """Gets the name of this PatchedOffice.  # noqa: E501

        The job's name.  # noqa: E501

        :return: The name of this PatchedOffice.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PatchedOffice.

        The job's name.  # noqa: E501

        :param name: The name of this PatchedOffice.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def location(self):
        """Gets the location of this PatchedOffice.  # noqa: E501

        The candidate's location.  # noqa: E501

        :return: The location of this PatchedOffice.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this PatchedOffice.

        The candidate's location.  # noqa: E501

        :param location: The location of this PatchedOffice.  # noqa: E501
        :type: str
        """

        self._location = location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatchedOffice):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PatchedOffice):
            return True

        return self.to_dict() != other.to_dict()
