# coding: utf-8

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from MergeATSClient.configuration import Configuration


class Scorecard(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'remote_id': 'str',
        'application': 'str',
        'interview': 'str',
        'interviewer': 'str',
        'remote_created_at': 'datetime',
        'submitted_at': 'datetime',
        'overall_recommendation': 'OverallRecommendationEnum'
    }

    attribute_map = {
        'id': 'id',
        'remote_id': 'remote_id',
        'application': 'application',
        'interview': 'interview',
        'interviewer': 'interviewer',
        'remote_created_at': 'remote_created_at',
        'submitted_at': 'submitted_at',
        'overall_recommendation': 'overall_recommendation'
    }

    def __init__(self, id=None, remote_id=None, application=None, interview=None, interviewer=None, remote_created_at=None, submitted_at=None, overall_recommendation=None, local_vars_configuration=None):  # noqa: E501
        """Scorecard - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._remote_id = None
        self._application = None
        self._interview = None
        self._interviewer = None
        self._remote_created_at = None
        self._submitted_at = None
        self._overall_recommendation = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.remote_id = remote_id
        self.application = application
        self.interview = interview
        self.interviewer = interviewer
        self.remote_created_at = remote_created_at
        self.submitted_at = submitted_at
        self.overall_recommendation = overall_recommendation

    @property
    def id(self):
        """Gets the id of this Scorecard.  # noqa: E501


        :return: The id of this Scorecard.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Scorecard.


        :param id: The id of this Scorecard.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def remote_id(self):
        """Gets the remote_id of this Scorecard.  # noqa: E501

        The third-party API ID of the matching object.  # noqa: E501

        :return: The remote_id of this Scorecard.  # noqa: E501
        :rtype: str
        """
        return self._remote_id

    @remote_id.setter
    def remote_id(self, remote_id):
        """Sets the remote_id of this Scorecard.

        The third-party API ID of the matching object.  # noqa: E501

        :param remote_id: The remote_id of this Scorecard.  # noqa: E501
        :type: str
        """

        self._remote_id = remote_id

    @property
    def application(self):
        """Gets the application of this Scorecard.  # noqa: E501

        The application being scored.  # noqa: E501

        :return: The application of this Scorecard.  # noqa: E501
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this Scorecard.

        The application being scored.  # noqa: E501

        :param application: The application of this Scorecard.  # noqa: E501
        :type: str
        """

        self._application = application

    @property
    def interview(self):
        """Gets the interview of this Scorecard.  # noqa: E501

        The interview being scored.  # noqa: E501

        :return: The interview of this Scorecard.  # noqa: E501
        :rtype: str
        """
        return self._interview

    @interview.setter
    def interview(self, interview):
        """Sets the interview of this Scorecard.

        The interview being scored.  # noqa: E501

        :param interview: The interview of this Scorecard.  # noqa: E501
        :type: str
        """

        self._interview = interview

    @property
    def interviewer(self):
        """Gets the interviewer of this Scorecard.  # noqa: E501

        The interviewer doing the scoring.  # noqa: E501

        :return: The interviewer of this Scorecard.  # noqa: E501
        :rtype: str
        """
        return self._interviewer

    @interviewer.setter
    def interviewer(self, interviewer):
        """Sets the interviewer of this Scorecard.

        The interviewer doing the scoring.  # noqa: E501

        :param interviewer: The interviewer of this Scorecard.  # noqa: E501
        :type: str
        """

        self._interviewer = interviewer

    @property
    def remote_created_at(self):
        """Gets the remote_created_at of this Scorecard.  # noqa: E501

        When the third party's scorecard was created.  # noqa: E501

        :return: The remote_created_at of this Scorecard.  # noqa: E501
        :rtype: datetime
        """
        return self._remote_created_at

    @remote_created_at.setter
    def remote_created_at(self, remote_created_at):
        """Sets the remote_created_at of this Scorecard.

        When the third party's scorecard was created.  # noqa: E501

        :param remote_created_at: The remote_created_at of this Scorecard.  # noqa: E501
        :type: datetime
        """

        self._remote_created_at = remote_created_at

    @property
    def submitted_at(self):
        """Gets the submitted_at of this Scorecard.  # noqa: E501

        When the scorecard was submitted.  # noqa: E501

        :return: The submitted_at of this Scorecard.  # noqa: E501
        :rtype: datetime
        """
        return self._submitted_at

    @submitted_at.setter
    def submitted_at(self, submitted_at):
        """Sets the submitted_at of this Scorecard.

        When the scorecard was submitted.  # noqa: E501

        :param submitted_at: The submitted_at of this Scorecard.  # noqa: E501
        :type: datetime
        """

        self._submitted_at = submitted_at

    @property
    def overall_recommendation(self):
        """Gets the overall_recommendation of this Scorecard.  # noqa: E501

        The inteviewer's recommendation.  # noqa: E501

        :return: The overall_recommendation of this Scorecard.  # noqa: E501
        :rtype: OverallRecommendationEnum
        """
        return self._overall_recommendation

    @overall_recommendation.setter
    def overall_recommendation(self, overall_recommendation):
        """Sets the overall_recommendation of this Scorecard.

        The inteviewer's recommendation.  # noqa: E501

        :param overall_recommendation: The overall_recommendation of this Scorecard.  # noqa: E501
        :type: OverallRecommendationEnum
        """

        self._overall_recommendation = overall_recommendation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Scorecard):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Scorecard):
            return True

        return self.to_dict() != other.to_dict()
