# flake8: noqa

"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.3.0"

# import ApiClient
from MergeATSClient.api_client import ApiClient

# import Configuration
from MergeATSClient.configuration import Configuration

# import exceptions
from MergeATSClient.exceptions import OpenApiException
from MergeATSClient.exceptions import ApiAttributeError
from MergeATSClient.exceptions import ApiTypeError
from MergeATSClient.exceptions import ApiValueError
from MergeATSClient.exceptions import ApiKeyError
from MergeATSClient.exceptions import ApiException
